service: twitter-bot
app: my-lambda-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  profile: serverless

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  tweet:
    handler: bin/tweet
    environment:
      ACCESS_TOKEN: ${ssm:/twitter/accessToken}
      ACCESS_TOKEN_SECRET: ${ssm:/twitter/accessTokenSecret}
      CONSUMER_KEY: ${ssm:/twitter/consumerKey}
      CONSUMER_SECRET: ${ssm:/twitter/consumerSecret}
      APIKEY: ${ssm:/twitter/a3rt/apikey}
    events:
      - schedule: rate(1 hour)
